### ISSUE TITLE
Namespace registration returns: unknown service

### ISSUE THREAD

**Issue by hazcod** [temporalio/temporal-go-sdk#163]
## Expected Behavior
Successfully register a new temporal namespace.

## Actual Behavior
client.Register returns error `unknown service temporal.workflowservice.v1.WorkflowService`

## Steps to Reproduce the Problem
```go
func (b *WorkflowClientBuilder) CreateNamespace(logger *zap.Logger, namespace string, wfRetention uint32) error {
	client, err := client.NewNamespaceClient(client.Options{HostPort: b.hostPort})
	if err != nil {
		logger.Error("failed to create Namespace Client", zap.Error(err))
		return err
	}
	defer client.Close()
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	err = client.Register(ctx, &workflowservice.RegisterNamespaceRequest{
		Name: namespace,
		WorkflowExecutionRetentionPeriodInDays: int32(wfRetention),
	})
	if err == nil {
		logger.Info("Namespace created")
		return nil
	}
	if _, ok := err.(*serviceerror.NamespaceAlreadyExists); ok {
		logger.Info("Namespace already exists")
		return nil
	}
	return err
}
```

## Specifications
```
	go.temporal.io/temporal v0.24.4
	go.temporal.io/temporal-proto v0.24.4
```

temporalio/auto-setup:0.23.1

**Comment by hazcod** [comment]
I have the same issue when creating a new workflow.

**Comment by plaisted** [comment]
I had this issue using mismatched versions as well, there must have been some breaking changes.  If you downgrade your go libraries to match the docker images (0.23.1) it worked as expected for me.

**Comment by hazcod** [comment]
@plaisted indeed! I used :latest Docker tag & Go .24 and things seemed to magically work..

**Comment by ringods** [comment]
For other people bumping into this, it could also mean that it just can't connect to the Temporal frontend service. Check the value of host and port your client or worker connects to if this error occurs.

My encounter with this error:
https://community.temporal.io/t/error-unknown-service-workflowservice-workflowservice/103/2
