### ISSUE TITLE
Change client.NewClient signature

### ISSUE THREAD

**Issue by alexshtin** [temporalio/temporal-go-sdk#39]
Currently we have only [one way](https://github.com/temporalio/temporal-go-client/blob/master/client/client.go#L402) to construct go client:
```
func NewClient(service workflowservice.WorkflowServiceClient, domain string, options *Options) Client
```
And every caller (customer code) has to do something like [this](https://github.com/temporalio/temporal-go-samples/blob/master/cmd/samples/common/factory.go#L92):
```
	connection, err := grpc.Dial(hostPort, grpc.WithInsecure())
	if err != nil {
		// log error
	}

	client := client.NewClient(workflowservice.NewWorkflowServiceClient(connection, "domain", options))
```
This is overwhelming and requires deep understanding of go-client internals. Also, now I need to add mandatory interceptors (for error conversion, metrics, and client version headers) and configure default round robin load balancing, which can be done only using `grpc.DialOptions`.

The proposal is to change `NewClient` signature to:
```
func  NewClient(hostPort, domain string, options *Options) Client
```
and add `GRPCOptions []grpc.DialOptions` to [Options](https://github.com/temporalio/temporal-go-client/blob/master/internal/client.go#L323).

Internally `NewClient` will merge passed `GRPCOptions` with default mandatory ones. This will keep same extensibility level, hide complexity, and set reasonable defaults.

**Comment by mfateev** [comment]
I propose to have three separate methods (naming is open for discussion):
```
NewClientLocal(domain string) Client
NewClientByAddress(hostPort, domain string, options *Options) Client
NewClientFromGRPC(service workflowservice.WorkflowServiceClient, domain string, options *Options) Client
```

**Comment by alexshtin** [comment]
Replace `status` with `serviceerror` everywhere in client and [here](https://github.com/temporalio/temporal/blob/master/tools/cli/app_test.go) after implementation.

**Comment by alexshtin** [comment]
We can't continue to support this:
```
NewClientFromGRPC(service workflowservice.WorkflowServiceClient, domain string, options *Options) Client
```
because there is no way to add interceptors when you have only client interface and not a connection itself. Actually they can not be even added to existing connection, therefore connection needs to be created internally.

Honestly, I don't see why we we might need to pass `workflowservice.WorkflowServiceClient`. There is no way to create it besides one single constructor which accepts only connection. And the only way to customize connection creation is to pass `grpc.DialOptions`.
